#include "src/game/envfx_snow.h"

const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_Eyes_Half_Closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_Eyes_Closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_Eyes_Closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_Eyes_Closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_Eyes_Closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_Eyes_Closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_Eyes_Dead_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_Head_Capless_Armature[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -32, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt1),
			GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt2),
			GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt3),
			GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt4),
			GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt5),
			GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt6),
			GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Eye_Material_Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_Left_Hand_Open_Armature[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, squishy_classic_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_Right_Hand_Open_Armature[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, squishy_classic_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_Right_Hand_Peace_Armature[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, squishy_classic_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_Right_Hand_Cap_Armature[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, squishy_classic_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_Right_Hand_Wing_Cap_Armature[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, squishy_classic_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_classic_Switch_Option_Right_Hand_Wing_Cap_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_Eyes_Half_Closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_Eyes_Closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_Eyes_Closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_Eyes_Closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_Eyes_Closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_Eyes_Closed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_Eyes_Dead_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_squishy_classic_Head_Capless_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -32, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt1),
				GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt2),
				GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt3),
				GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt4),
				GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt5),
				GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt6),
				GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Eye_Material_Switch_opt7),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_squishy_classic_Left_Hand_Open_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, squishy_classic_Switch_Option_Left_Hand_Open_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_squishy_classic_Right_Hand_Open_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, squishy_classic_Switch_Option_Right_Hand_Open_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_squishy_classic_Right_Hand_Peace_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, squishy_classic_Switch_Option_Right_Hand_Peace_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_squishy_classic_Right_Hand_Cap_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, squishy_classic_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_squishy_classic_Right_Hand_Wing_Cap_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, squishy_classic_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Switch_Option_Right_Hand_Wing_Cap_Wings_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Head_DL_mesh_layer_1_mat_override_Eyes_Half_Closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Head_DL_mesh_layer_1_mat_override_Mouth_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Head_DL_mesh_layer_1_mat_override_Mouth_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Head_DL_mesh_layer_1_mat_override_Mouth_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Head_DL_mesh_layer_1_mat_override_Mouth_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Head_DL_mesh_layer_1_mat_override_Mouth_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Head_DL_mesh_layer_1_mat_override_Wario_Mouth_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 62, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_classic_Butt_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 104, 0, 0, squishy_classic_Torso_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 123, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Head_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt1),
											GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt2),
											GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt3),
											GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt4),
											GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt5),
											GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt6),
											GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_squishy_classic_Head_Capless_Armature),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 110, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Left_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 110, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Right_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 71, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_classic_Left_Arm_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, squishy_classic_Left_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 115, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Left_Hand_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_squishy_classic_Left_Hand_Open_Armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 72, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_classic_Right_Arm_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, squishy_classic_Right_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 115, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Right_Hand_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, -68, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_squishy_classic_Right_Hand_Open_Armature),
										GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_squishy_classic_Right_Hand_Peace_Armature),
										GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_squishy_classic_Right_Hand_Cap_Armature),
										GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_squishy_classic_Right_Hand_Wing_Cap_Armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -2, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_classic_Left_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 101, 0, 0, squishy_classic_Left_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 98, 0, 0, squishy_classic_Left_Foot_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -2, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_classic_Right_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 101, 0, 0, squishy_classic_Right_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 98, 0, 0, 0, 0, 1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Right_Foot_DL_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_squishy_classic_Head_Capless_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -32, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_Metal_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_squishy_classic_Left_Hand_Open_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, squishy_classic_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_squishy_classic_Right_Hand_Open_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, squishy_classic_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal_0),
			GEO_OPEN_NODE(),
				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_squishy_classic_Right_Hand_Peace_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, squishy_classic_Switch_Option_Right_Hand_Peace_mesh_layer_1_mat_override_Metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_squishy_classic_Right_Hand_Cap_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, squishy_classic_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_Metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_squishy_classic_Right_Hand_Wing_Cap_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, squishy_classic_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1_mat_override_Metal_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_classic_Switch_Option_Right_Hand_Wing_Cap_Wings_mesh_layer_4_mat_override_Metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 62, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_classic_Butt_mesh_layer_1_mat_override_Metal_0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 104, 0, 0, squishy_classic_Torso_mesh_layer_1_mat_override_Metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 123, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Head_DL_mesh_layer_1_mat_override_Metal_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_squishy_classic_Head_Capless_Armature),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 110, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_classic_Left_Wing_DL_mesh_layer_4_mat_override_Metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 110, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_classic_Right_Wing_DL_mesh_layer_4_mat_override_Metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 71, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_classic_Left_Arm_Color_mesh_layer_1_mat_override_Metal_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, squishy_classic_Left_Forearm_mesh_layer_1_mat_override_Metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 115, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Left_Hand_DL_mesh_layer_1_mat_override_Metal_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_squishy_classic_Left_Hand_Open_Armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 72, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_classic_Right_Arm_Color_mesh_layer_1_mat_override_Metal_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, squishy_classic_Right_Forearm_mesh_layer_1_mat_override_Metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 115, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Right_Hand_DL_mesh_layer_1_mat_override_Metal_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, -68, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_squishy_classic_Right_Hand_Open_Armature),
										GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_squishy_classic_Right_Hand_Peace_Armature),
										GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_squishy_classic_Right_Hand_Cap_Armature),
										GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_squishy_classic_Right_Hand_Wing_Cap_Armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -2, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_classic_Left_Thigh_Color_mesh_layer_1_mat_override_Metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 101, 0, 0, squishy_classic_Left_Leg_mesh_layer_1_mat_override_Metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 98, 0, 0, squishy_classic_Left_Foot_mesh_layer_1_mat_override_Metal_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -2, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_classic_Right_Thigh_Color_mesh_layer_1_mat_override_Metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 101, 0, 0, squishy_classic_Right_Leg_mesh_layer_1_mat_override_Metal_0),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 98, 0, 0, 0, 0, 1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Right_Foot_DL_mesh_layer_1_mat_override_Metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_squishy_classic_Head_Capless_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -32, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Switch_Option_Head_Capless_DL_mesh_layer_1_mat_override_Metal_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_squishy_classic_Left_Hand_Open_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, squishy_classic_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_squishy_classic_Right_Hand_Open_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, squishy_classic_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal_0),
			GEO_OPEN_NODE(),
				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_squishy_classic_Right_Hand_Peace_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, squishy_classic_Switch_Option_Right_Hand_Peace_mesh_layer_1_mat_override_Metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_squishy_classic_Right_Hand_Cap_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, squishy_classic_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_Metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_squishy_classic_Right_Hand_Wing_Cap_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -13, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, squishy_classic_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1_mat_override_Metal_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Switch_Option_Right_Hand_Wing_Cap_Wings_mesh_layer_4_mat_override_Metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 62, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_classic_Butt_mesh_layer_1_mat_override_Metal_0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 104, 0, 0, squishy_classic_Torso_mesh_layer_1_mat_override_Metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 123, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Head_DL_mesh_layer_1_mat_override_Metal_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_squishy_classic_Head_Capless_Armature),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 110, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Left_Wing_DL_mesh_layer_4_mat_override_Metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 110, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Right_Wing_DL_mesh_layer_4_mat_override_Metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 71, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_classic_Left_Arm_Color_mesh_layer_1_mat_override_Metal_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, squishy_classic_Left_Forearm_mesh_layer_1_mat_override_Metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 115, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Left_Hand_DL_mesh_layer_1_mat_override_Metal_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_squishy_classic_Left_Hand_Open_Armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 72, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_classic_Right_Arm_Color_mesh_layer_1_mat_override_Metal_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, squishy_classic_Right_Forearm_mesh_layer_1_mat_override_Metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 115, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Right_Hand_DL_mesh_layer_1_mat_override_Metal_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, -68, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_squishy_classic_Right_Hand_Open_Armature),
										GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_squishy_classic_Right_Hand_Peace_Armature),
										GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_squishy_classic_Right_Hand_Cap_Armature),
										GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_squishy_classic_Right_Hand_Wing_Cap_Armature),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -2, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_classic_Left_Thigh_Color_mesh_layer_1_mat_override_Metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 101, 0, 0, squishy_classic_Left_Leg_mesh_layer_1_mat_override_Metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 98, 0, 0, squishy_classic_Left_Foot_mesh_layer_1_mat_override_Metal_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -2, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_classic_Right_Thigh_Color_mesh_layer_1_mat_override_Metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 101, 0, 0, squishy_classic_Right_Leg_mesh_layer_1_mat_override_Metal_0),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 98, 0, 0, 0, 0, 1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_Right_Foot_DL_mesh_layer_1_mat_override_Metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Head_DL_mesh_layer_1_mat_override_Eyes_Half_Closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Head_DL_mesh_layer_1_mat_override_Mouth_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Head_DL_mesh_layer_1_mat_override_Mouth_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Head_DL_mesh_layer_1_mat_override_Mouth_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Head_DL_mesh_layer_1_mat_override_Mouth_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Head_DL_mesh_layer_1_mat_override_Mouth_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Head_DL_mesh_layer_1_mat_override_Wario_Mouth_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_classic_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 62, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_classic_Butt_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 104, 0, 0, squishy_classic_Torso_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 123, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Head_DL_mesh_layer_1),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt1),
																	GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt2),
																	GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt3),
																	GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt4),
																	GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt5),
																	GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt6),
																	GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt7),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, squishy_classic_Head_Capless_Armature),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 110, -51, 126, -15, 33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_classic_Left_Wing_DL_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 110, -51, -126, 15, -33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_classic_Right_Wing_DL_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 71, -10, 79, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_classic_Left_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, squishy_classic_Left_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(1, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 115, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(1, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Left_Hand_DL_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, squishy_classic_Left_Hand_Open_Armature),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 72, -10, -79, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_classic_Right_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, squishy_classic_Right_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 115, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(0, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Right_Hand_DL_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																		GEO_HELD_OBJECT(0, -68, 0, 0, geo_switch_mario_hand_grab_pos),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, squishy_classic_Right_Hand_Open_Armature),
																GEO_BRANCH(1, squishy_classic_Right_Hand_Peace_Armature),
																GEO_BRANCH(1, squishy_classic_Right_Hand_Cap_Armature),
																GEO_BRANCH(1, squishy_classic_Right_Hand_Wing_Cap_Armature),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -2, -8, 42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_classic_Left_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 101, 0, 0, squishy_classic_Left_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 98, 0, 0, squishy_classic_Left_Foot_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -2, -8, -42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_classic_Right_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 101, 0, 0, squishy_classic_Right_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 98, 0, 0, 0, 0, 1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(2, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_Right_Foot_DL_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1),
							GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2),
							GEO_BRANCH(1, squishy_classic_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_classic_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_classic_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_classic_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
